// Fuente de verdad para servicios conocidos. Usada por GmailDatasource,
// ServiceLogo y el autocomplete de AddSubscriptionPage.

/// keyword (lowercase) → nombre para mostrar
const Map<String, String> kKnownServices = {
  'netflix': 'Netflix',
  'spotify': 'Spotify',
  'amazon prime': 'Amazon Prime',
  'amazon': 'Amazon',
  'disney': 'Disney+',
  'hulu': 'Hulu',
  'hbo': 'HBO Max',
  'hbo max': 'HBO Max',
  'max streaming': 'MAX',
  'max.com': 'MAX',
  'paramount': 'Paramount+',
  'apple tv': 'Apple TV+',
  'apple music': 'Apple Music',
  'apple one': 'Apple One',
  'youtube': 'YouTube Premium',
  'twitch': 'Twitch',
  'crunchyroll': 'Crunchyroll',
  'deezer': 'Deezer',
  'tidal': 'Tidal',
  'adobe': 'Adobe Creative Cloud',
  'microsoft': 'Microsoft 365',
  'office': 'Microsoft 365',
  'github': 'GitHub',
  'notion': 'Notion',
  'dropbox': 'Dropbox',
  'duolingo': 'Duolingo Plus',
  'canva': 'Canva Pro',
  'chatgpt': 'ChatGPT Plus',
  'openai': 'ChatGPT Plus',
  'anthropic': 'Anthropic',
  'figma': 'Figma',
  'slack': 'Slack',
  'zoom': 'Zoom',
  'xbox': 'Xbox Game Pass',
  'pc game pass': 'Xbox Game Pass',
  'game pass': 'Xbox Game Pass',
  'playstation': 'PlayStation Plus',
  'nintendo': 'Nintendo Switch Online',
};

/// Nombres únicos para el picker (ordenados).
final List<String> kKnownServiceNames = kKnownServices.values.toSet().toList()
  ..sort();

/// Categoría sugerida por servicio (coincide con las categorías de la app).
const Map<String, String> kServiceCategories = {
  'Netflix': 'Entretenimiento',
  'Spotify': 'Música',
  'Amazon Prime': 'Entretenimiento',
  'Amazon': 'Otro',
  'Disney+': 'Entretenimiento',
  'Hulu': 'Entretenimiento',
  'HBO Max': 'Entretenimiento',
  'MAX': 'Entretenimiento',
  'Paramount+': 'Entretenimiento',
  'Apple TV+': 'Entretenimiento',
  'Apple Music': 'Música',
  'Apple One': 'Entretenimiento',
  'YouTube Premium': 'Entretenimiento',
  'Twitch': 'Entretenimiento',
  'Crunchyroll': 'Entretenimiento',
  'Deezer': 'Música',
  'Tidal': 'Música',
  'Adobe Creative Cloud': 'Productividad',
  'Microsoft 365': 'Productividad',
  'GitHub': 'Productividad',
  'Notion': 'Productividad',
  'Dropbox': 'Productividad',
  'Duolingo Plus': 'Educación',
  'Canva Pro': 'Productividad',
  'ChatGPT Plus': 'Productividad',
  'Anthropic': 'Productividad',
  'Figma': 'Productividad',
  'Slack': 'Productividad',
  'Zoom': 'Productividad',
  'Xbox Game Pass': 'Entretenimiento',
  'PlayStation Plus': 'Entretenimiento',
  'Nintendo Switch Online': 'Entretenimiento',
};
